android.enableR8.fullMode=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-XX:+UseG1GC -Xmx4096m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
kotlin.daemon.jvm.options=-XX:+UseG1GC -Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.warning.mode=summary

debug.local.host=http://192.168.0.248:9000