package com.grappim.taigamobile.feature.projects.domain

enum class TaigaPermission {
    VIEW_PROJECT,

    VIEW_MILESTONES,
    ADD_MILESTONE,
    MODIFY_MILESTONE,
    DELETE_MILESTONE,

    VIEW_EPICS,
    ADD_EPIC,
    MODIFY_EPIC,
    COMMENT_EPIC,
    DELETE_EPIC,

    VIEW_US,
    ADD_US,
    MODIFY_US,
    COMMENT_US,
    DELETE_US,

    VIEW_TASKS,
    ADD_TASK,
    MODIFY_TASK,
    COMMENT_TASK,
    DELETE_TASK,

    VIEW_ISSUES,
    ADD_ISSUE,
    MODIFY_ISSUE,
    COMMENT_ISSUE,
    DELETE_ISSUE,

    VIEW_WIKI_PAGES,
    ADD_WIKI_PAGE,
    MODIFY_WIKI_PAGE,
    COMMENT_WIKI_PAGE,
    DELETE_WIKI_PAGE,

    VIEW_WIKI_LINKS,
    ADD_WIKI_LINK,
    MODIFY_WIKI_LINK,
    DELETE_WIKI_LINK,

    MODIFY_PROJECT,
    DELETE_PROJECT,
    ADD_MEMBER,
    REMOVE_MEMBER,
    ADMIN_PROJECT_VALUES,
    ADMIN_ROLES
}
