name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        env:
            TAIGA_PATH_R: ${{ secrets.TAIGA_PATH_R }}
            TAIGA_KEY_PASS_R: ${{ secrets.TAIGA_KEY_PASS_R }}
            TAIGA_STORE_PASS_R: ${{ secrets.TAIGA_STORE_PASS_R }}
            TAIGA_ALIAS_R: ${{ secrets.TAIGA_ALIAS_R }}
            ENCODED_STRING_R: ${{ secrets.TAIGA_KEYSTORE_R }}
            TAIGA_PATH_D: ${{ secrets.TAIGA_PATH_D }}
            TAIGA_KEY_PASS_D: ${{ secrets.TAIGA_KEY_PASS_D }}
            TAIGA_STORE_PASS_D: ${{ secrets.TAIGA_STORE_PASS_D }}
            TAIGA_ALIAS_D: ${{ secrets.TAIGA_ALIAS_D }}
            ENCODED_STRING_D: ${{ secrets.TAIGA_KEYSTORE_D }}

            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Check out the repo
              uses: actions/checkout@v6

            - name: Setup Android Environment
              uses: ./.github/actions/android-setup-composite-action

            - name: Restore taigamobilenova_keystore_release.jks
              run: echo $ENCODED_STRING_R | base64 -d > ./taigamobilenova_keystore_release.jks

            - name: Restore taigamobilenova_debug.jks
              run: echo $ENCODED_STRING_D | base64 -d > ./taigamobilenova_debug.jks

            - name: Build Release Fdroid APK
              run: |
                  ./gradlew :androidApp:assembleFdroidRelease :androidApp:assembleFdroidDebug

            - name: Build Release Gplay APK and AAB
              run: |
                  ./gradlew :androidApp:assembleGplayRelease :androidApp:bundleGplayRelease -PgplayBuild

            - name: Upload Release Build To Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: release-artifacts
                  path: |
                      androidApp/build/outputs/apk/*
                      androidApp/build/outputs/bundle/*

            - name: Create GitHub release
              uses: softprops/action-gh-release@v2
              with:
                  generate_release_notes: true
                  draft: false
                  make_latest: true
                  preserve_order: true
                  files: |
                      androidApp/build/outputs/apk/fdroid/release/app-fdroid-release.apk
                      androidApp/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
                      androidApp/build/outputs/apk/gplay/release/app-gplay-release.apk
                      androidApp/build/outputs/bundle/gplayRelease/androidApp-gplay-release.aab